### ISSUE TITLE
Improvements for v2

### ISSUE THREAD

**Issue by hrjn** [dataiku/dss-plugin-aks-clusters#1]
## TODO

- [x] Use DSS host's VNET/subnet by default for node pools
- [x] Refactor with ClusterBuilder and NodePoolBuilder
- [x] Restore GUID stuff for consumption tracking 
- [x] Add the k8s version option in the cluster UI (`azure.mgmt.containerservice.models.ManagedCluster.kubernetes_version`)
- [x] Option "use specific SP for cluster" disabled by default, conditions cluster SP dropdown visibility
- [ ] "Add node pool" macro
- [ ] GPU support
- [ ] Documentation draft in R&D wiki

--- 
- [ ] Create cluster SP on-the-fly using az create-for-rbac [[example](https://github.com/Azure/vagrant-azure/issues/164)]
- [ ] Better handling of AKS API create/delete callbacks
- [ ] Clean up "zombie" clusters and reset (DSS) cluster status
